Use the master_key instead of the app_key
this commit revert the change in commit
2118a052c5d0018005553f7e5b3dc8a79070e629, or you'll get the error:
> LeanCloudError: [1] Forbidden to delete by class permissions.